### ISSUE TITLE
JSON parsing error with `get_player_details()`

### ISSUE THREAD

**Issue by gtm19** [wiscostret/fplscrapR#12] opened 2020-01-26 20:21 UTC
Getting the following error when trying to render an `.Rmd` code block containing `fplscrapR::get_player_details()` with no arguments (so as to return this seasons' stats)
```
Rendering 2020-01-25-fantasy-premier-league-1.Rmd
Quitting from lines 67-72 (2020-01-25-fantasy-premier-league-1.Rmd) 
Error in parse_con(txt, bigint_as_char) : parse error: premature EOF
                                       
                     (right here) ------^
Calls: local ... <Anonymous> -> parse_and_simplify -> parseJSON -> parse_con
Execution halted
```

**Comment by wiscostret** [comment] 2020-01-27 08:46
Have you updated/installed the package recently? We pushed an update to the package on 10 Jan which solved an issue with get_player_details()

**Comment by gtm19** [comment] 2020-01-27 09:03
@wiscostret I installed it for the first time yesterday. 

From a bit of Googling, `premature EOF` looks like a common error when querying APIs for JSON, where the connection is interrupted or refused. Since this command works when I run it interactively in R, but errors when I try to knit the RMarkdown file, my guess is that FPL's API endpoint is refusing the connection.

**Comment by wiscostret** [comment] 2020-01-27 12:06
Thanks. Occasionally the API will refuse a connection but if the issue is consistent, I think it's likely to do with the parsing rather than your choice of console. Other users have recently reported issues with parsing from the API using the fplscrapR package, though I have not yet been able to reproduce the issues. Will take an extra look as soon as possible.

**Comment by wiscostret** [comment] 2020-07-28 09:01
Hi, sorry for getting back to this late, was just reviewing issues again. Is this still a problem? I wasn´t able to find an reproducible issue on the parsing.

**Comment by gtm19** [comment] 2020-07-29 07:47
I'd say you can probably close it.

I can still replicate the issue, but _only_ by clicking <kbd>Knit</kbd> at the top of RStudio. The error does not occur when running `rmarkdown::render()` in the R console. 

This is odd, because it appears that clicking <kbd>Knit</kbd> should call the `render()` function, but :man_shrugging:.

Either way I think it's an RStudio issue. Perhaps even [this one in particular](https://github.com/rstudio/rstudio/issues/7003).

**Comment by wiscostret** [comment] 2020-07-31 11:45
Huh, strange one. Thanks for the info - I will close this issue but look into it further, see if there´s anything I can do for the next package update.

**Closed as completed by wiscostret** 2020-07-31 11:45 UTC
